### ISSUE TITLE
Show person information upon clicking on her

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#12]
Person's full information:
https://www.figma.com/file/QBwhX10crf6NpRwNn3eASIUK/Arcadia-Assistant?node-id=1%3A7

**Comment by KuchaLeni** [comment]
Related issue: #152

**Comment by KuchaLeni** [comment]
![person_info](https://user-images.githubusercontent.com/28759011/41534982-40de05e8-7309-11e8-8642-473e222605bb.jpg)
