### ISSUE TITLE
Incorrect list of employees is displayed in some cases

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#150]
Precondition: close the application if it's open
1. Open the app
2. Go to Profile page -> Organization
3. Swipe in 'directors' or higher levels 

Result:
Incorrect list of employees for first manager in the list is displayed (in attachment - displays 3 person instead of 30)
![bug](https://user-images.githubusercontent.com/28759011/41191205-b2dfa60e-6bf4-11e8-87fa-21312d50ac6b.jpg)

**Comment by santee** [comment]
@KuchaLeni still relevant?

**Comment by KuchaLeni** [comment]
List of employees is loading partly. So when user opens the app not from background, he can see the 2 part of employee list loading (now it more faster then in build when bug was created). See attach employee_list.zip.
[employee_list.zip](https://github.com/SoftwareCountry/arcadian-assistant/files/2581400/employee_list.zip)

@santee  if it's ok, I can close the bug.

**Comment by santee** [comment]
it's ok

**Comment by KuchaLeni** [comment]
Closed due to comment above
