### ISSUE TITLE
Remove vertical stripes from selection in Calendar

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#154]
1. Open calendar
2. Request Vacation or claim sick leave
3. Select date range

Result: date range selection with vertical stripes

Expected result: date range selection without vertical stripes

![calendar](https://user-images.githubusercontent.com/28759011/41353291-85ef510c-6f24-11e8-933e-e816b418e12a.jpg)

**Comment by serjKim** [comment]
Relates to [https://github.com/facebook/react-native/issues/18137](url)

**Comment by KuchaLeni** [comment]
Fixed.
![calendar](https://user-images.githubusercontent.com/28759011/48493957-e8222100-e83d-11e8-9aca-4c41aab5704f.jpg)
