### ISSUE TITLE
Add search on pages "Feeds" and "People"

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#157]
![search](https://user-images.githubusercontent.com/28759011/41413965-6ba39564-6fed-11e8-9e47-8499637fdcd3.png)
![search2](https://user-images.githubusercontent.com/28759011/41413967-6bc97c52-6fed-11e8-92a1-a7b88152828a.png)

**Comment by KuchaLeni** [comment]
Feed view has no search functionality. @santee , will it be added?

**Comment by santee** [comment]
not now, it won't

**Comment by KuchaLeni** [comment]
Closed due to comment above.
