### ISSUE TITLE
Calendar view: Not possible to click on 'Edit' button for approved events

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#159]
1. Open app -> calendar view
2. Click on approved day off or completed Sick leave day
3. Click on 'Edit dayoff' or 'Edit Sick leave'

Result: nothing happens 

Expected result: opens popup for event editing  
![edit_button](https://user-images.githubusercontent.com/28759011/41547587-41a2bd78-7329-11e8-8f1d-7740f4c3a74e.jpg)
![edit_button2](https://user-images.githubusercontent.com/28759011/41547594-4acc12b4-7329-11e8-82df-a5843b798f07.jpg)

**Comment by serjKim** [comment]
Decided to hide 'Edit' button for approved calendar event. But supervisor can see 'Reject' button for approved events on his Profile.

**Comment by KuchaLeni** [comment]
Corrected according to the comment above.
Closed.
