### ISSUE TITLE
Add logout icon on all pages

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#164]
Add logout icon on 'Feeds', 'People' and 'Calendar' pages 
![logout](https://user-images.githubusercontent.com/28759011/41596255-60eef120-73d2-11e8-978a-cd4188fb9a3c.jpg)

**Comment by KuchaLeni** [comment]
@santee  the logout icon was added on Profile view only. It's ok?

**Comment by santee** [comment]
yep. keep it like that for now

**Comment by KuchaLeni** [comment]
Closed due to comment above
