### ISSUE TITLE
Set real bundle identifiers for iOS&Android projects

### ISSUE THREAD

**Issue by victor-kotov-arcadia** [SoftwareCountry/arcadian-assistant#19]
Right now mobile projects have generic bundle identifiers forged by ReactNative scripts. To be able to create app's profiles and setup CI environment we should change these generic values to some specific.

Suggestion:

com.arcadia.product.assistant.ios
com.arcadia.product.assistant.android

**Comment by santee** [comment]
ru.spb.arcadia. ? :)
