### ISSUE TITLE
Profile tab: Status bar should have colored background 

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#194]
Status bar should have colored background (Color: #2FAFCC) on Profile tab. 

![1](https://user-images.githubusercontent.com/28759011/43651307-ada3252c-974a-11e8-8798-29029b0b4ff3.png)
![2](https://user-images.githubusercontent.com/28759011/43651308-adbf4ca2-974a-11e8-988d-36a4fa2b9ee6.png)

**Comment by KuchaLeni** [comment]
The bug is reproduced.

**Comment by YaroTs** [comment]
develop/ 8468a62e0591a227fe94ee6d3c1980b6013c76f5

**Comment by KuchaLeni** [comment]
@santee, is it deployed? The bug is reproduced for iOS.

**Comment by KuchaLeni** [comment]
Verified.
