### ISSUE TITLE
Tab bar: second click on the icon should scroll to the top of the page

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#195]
After scrolling down, the user should be able to quickly scroll to the top of the page.
- On tabs 'Feeds', 'People', 'Profile' - second click leads to the top of the page.
- On tab 'Calendar' - second click opens month of the current date.

**Comment by YaroTs** [comment]
develop/ c8bb8714a515d07c2029bf65cbdf2059f09ad090

**Comment by KuchaLeni** [comment]
Double click doesn't work on People->Company view

**Comment by YaroTs** [comment]
develop/ e40a7373fd6939704f61da275942d5849287faf8

**Comment by KuchaLeni** [comment]
Verified.
