### ISSUE TITLE
Department list: Display employees from subdepartments

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#222]
Department list should display not only people from own department, but all subordinate departments as well. Possibly switch to the same view as company list.
NB: employee can be a member of only one department, but be a chief of multiple departments.

**Comment by antonm76** [comment]
@santee @mdraschinsky guys, could you please review #251 ? Looks like this one is redundant since People, Company view is refactored.

**Comment by antonm76** [comment]
@santee @mdraschinsky guys, I'm going to close it today.

**Comment by antonm76** [comment]
Invalid.
