### ISSUE TITLE
People.Company view: employee profile does not always open

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#225]
1) Open People tab -> Company tab
2) Click on an employee with chief role

Result: employee profile does not always open (see attach)
[company_view_video.zip](https://github.com/SoftwareCountry/arcadian-assistant/files/2576761/company_view_video.zip)

Expected result: employee profile opens after each click on employee

**Comment by santee** [comment]
@KuchaLeni

**Comment by KuchaLeni** [comment]
Verified.
