### ISSUE TITLE
People and Calendar views don't have loading indicator

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#228]
People and Calendar views don't have loading indicator.
- People view has unnecessary white line while page is loading  
![people](https://user-images.githubusercontent.com/28759011/48480791-94531000-e81c-11e8-9dd0-158008911790.png)

- Calendar view
![calendar](https://user-images.githubusercontent.com/28759011/48480792-94531000-e81c-11e8-8bc7-5424a1cd5330.png)

**Comment by KuchaLeni** [comment]
#153

**Comment by KuchaLeni** [comment]
Related bug #153

**Comment by DesmanLead** [comment]
Done in 73d7b7748596fcd69275cb4bf54d60dd896dd949

**Comment by KuchaLeni** [comment]
Verified.
