### ISSUE TITLE
Header is not displayed when profile view is loading

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#229]
![profile](https://user-images.githubusercontent.com/28759011/48484199-8f935980-e826-11e8-8fce-8155ba13252b.png)

**Comment by YaroTs** [comment]
develop/ 8468a62e0591a227fe94ee6d3c1980b6013c76f5

**Comment by KuchaLeni** [comment]
Related issue #297

**Comment by KuchaLeni** [comment]
Fixed.
