### ISSUE TITLE
Change approvers for department chiefs

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#230]
In case if employee is a chief of a department he belongs to, his calendar events should be approved by the chief of upper department (in case if there is any)

**Comment by sponkrashin** [comment]
The latest discussion results - need to implement 3 different kinds of behavior.

1. Current behavior - show pending requests only from current department (department where current user is head).
2. Plus dependent departments heads - show pending requests from current department + heads of dependent departments.
3. Plus all dependent employees - show pending requests from current department + all employees from all dependent departments.

**Comment by sponkrashin** [comment]
@KuchaLeni done.

**Comment by KuchaLeni** [comment]
Related issue #291

**Comment by sponkrashin** [comment]
It is not actual more. The approach to get pending actions for the person is fully refactored in #291
