### ISSUE TITLE
Add ping/health endpoint

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#231]
should be /health web endpoint, that returns a json with a result of
a) general status
b) server status
c) database/1c maybe?

**Comment by sponkrashin** [comment]
What do you mean by "general status"? Status of API should be determined from application itself. If it cannot get answer from this endpoint then status is not OK.

**Comment by santee** [comment]
general - is 'web' answering or not :) so, basically, by itself it should return 'i'm ok'

**Comment by sponkrashin** [comment]
Added "api/health" endpoint.

**Comment by KuchaLeni** [comment]
Verified
