### ISSUE TITLE
User preference screen

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#234]
1. Enable/disable push notifications
2. Enable/disable email notifications
~3. Three state switch or select for pending requests behavior: Show only current department employees, Show current department plus heads of dependent departments, show current department plus all employees from dependent departments~

Related issue #233

**Comment by antonm76** [comment]
Any mockups available?

**Comment by santee** [comment]
No :D

**Comment by antonm76** [comment]
Hmmm, great! I would like to implement it as a kitten! Everybody likes kittens! -)

**Comment by sponkrashin** [comment]
UPD: 3rd point in description is not needed more. Pending actions are implemented another way in #291, so this preference is redundant.

**Comment by YaroTs** [comment]
![screenshot 2018-12-03 at 14 43 20](https://user-images.githubusercontent.com/5641071/49455534-67c95d00-f7f8-11e8-9ccb-cacd8e3de9bc.png)
![screenshot 2018-12-03 at 14 43 31](https://user-images.githubusercontent.com/5641071/49455536-67c95d00-f7f8-11e8-984b-d36487bc784e.png)

**Comment by YaroTs** [comment]
43d92d217b574854fab628a920d075a95ecaec74

**Comment by KuchaLeni** [comment]
Reopened.
iOS: User's preferences is opened after the second click on icon. 
Android: 
- User's preferences icon is smaller than logout icon. 
- User's preferences opens once from ~20 clicks.
![arcadiaassistant](https://user-images.githubusercontent.com/28759011/50008921-9d273500-ffc6-11e8-9253-c278505136d8.jpg)

**Comment by YaroTs** [comment]
86f86024514169b6e282d464e0322c459e711316

**Comment by KuchaLeni** [comment]
Verified.
