### ISSUE TITLE
Add an HTML page with iPA/apk

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#236]

**Comment by sponkrashin** [comment]
Do we need links to applications or just file to download?
If links then where can I find them and do we need QR-codes also?

**Comment by santee** [comment]
i assume we'd have buttons 'download' There should be one ipa and one apk files. I have no files yet. Start with apk, it's easier.

**Comment by sponkrashin** [comment]
I can add properties in config to specify apk file path and ipa file path.

**Comment by KuchaLeni** [comment]
Verified
