### ISSUE TITLE
Some employees not displayed in list of employees from the same room

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#238]
For ex. open list for employees from 612 room. 
![612_room](https://user-images.githubusercontent.com/28759011/48548332-bf516880-e8dd-11e8-8996-1c48d61e4cfe.jpg)

The list for employees from DB
![612_from_db](https://user-images.githubusercontent.com/28759011/48548522-37b82980-e8de-11e8-8fba-f791cd7ce68d.png)

If user opens for employees employee profiles with id=514 and id=2218, the 'missed' employees would be displayed in list of employees from the same room

**Comment by KuchaLeni** [comment]
Related issue #239

**Comment by YaroTs** [comment]
develop/ 94c7d575010df80255626c52ab6ac59b58d7e257

**Comment by KuchaLeni** [comment]
Verified
