### ISSUE TITLE
Logout does not always work immediately

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#241]
Go to Profile view and log out from the app.
**Result:** Logout does not always work immediately. See attach 
[logout.zip](https://github.com/SoftwareCountry/arcadian-assistant/files/2585122/logout.zip)
**Expected result:** Logout works immediately

Post steps: 
Close and Open the app again. Welcome screen with login pop-up is opened 
![welcome_screen](https://user-images.githubusercontent.com/28759011/48551013-481fd280-e8e5-11e8-870c-f1ba4cf03446.jpg)

**Comment by KuchaLeni** [comment]
Related issue #162

**Comment by YaroTs** [comment]
I wasn't able to reproduce this issue. @KuchaLeni could you please check if this issue is still valid using latest develop commit?

Also, how many times have you tried to get it?

**Comment by antonm76** [comment]
@KuchaLeni any news?

**Comment by KuchaLeni** [comment]
I can reproduce it in build 114 for iOS and can't reproduce it in build 115.
Device - iphone 7plus, iOS 12.0

**Comment by KuchaLeni** [comment]
Bug is not reproduced.
Closed.
