### ISSUE TITLE
On Android feeds do not load next page when list is scrolled to the bottom

### ISSUE THREAD

**Issue by antonm76** [SoftwareCountry/arcadian-assistant#249]
@santee please assign a proper Milestone

**Comment by antonm76** [comment]
Done. develop/dc8c7d8c4669431dd56bf107458f96c0e6d8b6df

**Comment by KuchaLeni** [comment]
Reopened.
(device: OnePlus, android: 9)
Scroll the list of feeds to the bottom and check that loader icon is displayed. 
Result: The next page of feeds doesn't load until the user scrolls up.

**Comment by antonm76** [comment]
@KuchaLeni fixed in 57f6eebf7f5049a4b6be76ad7a2dae69e65bf75d

**Comment by KuchaLeni** [comment]
Verified.
