### ISSUE TITLE
Consider refactoring of the People, Company view

### ISSUE THREAD

**Issue by antonm76** [SoftwareCountry/arcadian-assistant#251]
Currently on the People, Company view most of the screen is occupied by the 4 fixed rows, it makes very a very few space for the 'sub-department' portion of the view:
- consider change a way ho 'sub-department' portion is scrolled: when scrolling up, consider to scroll upper 4 rows up as well to make bigger real estate.

@santee assign a proper milestone.

**Comment by santee** [comment]
@serjKim give your feedback how easy it is to achieve.

**Comment by DesmanLead** [comment]
Done easy way (wrapped into a ScrollView) in 394ca8aa941e77b04b0aae2ca6b7e318f3cffbb3

**Comment by antonm76** [comment]
@DesmanLead on iPhone when you scroll people horizontally and at the same time accidentally move finger a bit in vertical direction, horizontal scroll view stuck (@santee noticed that). It doesn't reproduce on Android.

**Comment by DesmanLead** [comment]
Fixed in 665d002a32c5caa26a3a210ace733354c584b06d

**Comment by KuchaLeni** [comment]
Blocker #277

**Comment by KuchaLeni** [comment]
Verified.
