### ISSUE TITLE
Consider replacing a Search button pin the top with the Search text input

### ISSUE THREAD

**Issue by antonm76** [SoftwareCountry/arcadian-assistant#252]
Having a Search button on the Navigation bar which opens a Search text input looks like a bad design idea, consider replacing a button with just a Search text input (refer to Twitter app, for example)

@santee assign a proper milestone

**Comment by santee** [comment]
the bigger problem with search is that right now it searches over loaded people only (its client side). This problem is relevant for Company view only

**Comment by KuchaLeni** [comment]
Fixed
