### ISSUE TITLE
Add department abbreviation and room number to department and room titles 

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#258]
![titles](https://user-images.githubusercontent.com/28759011/48703899-38b2c900-ec06-11e8-8e97-728efa42aa63.png)
Related issue #223

**Comment by antonm76** [comment]
Done. c03a6658c09fcd6365e5e05cc59e42c69e96c819

**Comment by KuchaLeni** [comment]
Verified.
