### ISSUE TITLE
Android: add swipe navigation

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#261]
Navigation 'Back' is available only by clicking on back arrow (see screenshot). Need to add swipe navigation as on iOS
![navigation](https://user-images.githubusercontent.com/28759011/48716586-bb4c8000-ec28-11e8-9388-8bf14e0ddb0d.png)

**Comment by DesmanLead** [comment]
@KuchaLeni it is an iOS-specific feature. Android way to provide easy navigation is the hardware 'back' button.

**Comment by DesmanLead** [comment]
@sponkrashin sure it can be done in some of many third-party UI extensions. So does it allow you to navigate back in Arcadian Assistant with a swipe?

**Comment by antonm76** [comment]
> But my Android allows me to do swipe left to navigate to previous view.

It still doesn't mean it is a natural Android's behaviour.
