### ISSUE TITLE
Page refreshing does not update employee information

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#287]
1) Open the app and go to the Profile view
2) Go to DB and change some employee information (for ex. department 'SDO.822'->'SDO.822.COV')
3) Update the view by swiping down

Result: Info on profile view is not updated
![1](https://user-images.githubusercontent.com/28759011/49027556-7b9a1100-f1b1-11e8-9a26-4dc526bfc693.png)

Expected result: Page refreshing is updates employee information

Post-steps:
1) Go to people view -> department
2) Note that department is updated.
![2](https://user-images.githubusercontent.com/28759011/49027569-85237900-f1b1-11e8-9a43-c40603e0ef16.png)

**Comment by KuchaLeni** [comment]
The same problem on Feeds view. 
@DesmanLead can you fix updating feeds on Feeds view within this issue?

**Comment by antonm76** [comment]
@KuchaLeni what do you mean the same issue? I do not see any department info on the Feeds view. Do you mean department info on the employee view?

**Comment by KuchaLeni** [comment]
> Go to DB and change some employee information 
The problem not only with department (it was just example) but also with email, phone number, etc.

The problem on Feeds view -> new feeds are not uploaded after page refreshing (swipe down). New feed are displayed only after closing and opening the app.

**Comment by KuchaLeni** [comment]
@DesmanLead ok.
