### ISSUE TITLE
Refine vacations pipeline

### ISSUE THREAD

**Issue by sponkrashin** [SoftwareCountry/arcadian-assistant#291]
In the end all vacation requests should be approved by employee with director role. Some employees could also need for an approval by employee with manager role.
When manager approval is required, director shouldn't see concrete pending request until manager approves it. But director can still approve it directly from concrete employee page.
After manager approves request, director will see appropriate request in his pending requests queue.

**Comment by sponkrashin** [comment]
Logic of approvers definitions is the following:
First need to get employee's department. Then we have some cases:
1) Department is SDO.*.* and employee is not head - need approval of department head and parent department head
2) Department is SDO.*.* and employee is head - need approval of parent department head
3) All other departments and employee is not head - need approval of current department head
4) All other departments and employee is head - need approval of parent department head
5) Director General - don't need approval

**Comment by sponkrashin** [comment]
Logic for vacations is described above. Logic for all other event types is more simple: only current department chief (or parent department chief, if employee is also a chief) is required.

**Comment by KuchaLeni** [comment]
Verified
