### ISSUE TITLE
Support new permission: Cancel approved vacations

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#300]
Only supervisor should be able to cancel fully APPROVED vacation.
Not yet approved vacations can be canceled by employee himself.
Corresponding information should be returned on a client.

**Comment by santee** [comment]
Only supervisor should be able to cancel fully APPROVED vacation

**Comment by sponkrashin** [comment]
What about other approved events? Workouts, day offs and sick leaves.

**Comment by santee** [comment]
Let's implement the same logic for know

**Comment by sponkrashin** [comment]
Added new employee permission: CancelApprovedCalendarEvents, which is added only to supervisor employees.

**Comment by KuchaLeni** [comment]
Verified.
Supervisor can't cancel vacations with the status 'Processed'. 
Only HR can cancel 'Processed' vacation.
