### ISSUE TITLE
Only superviser should be able to cancel APPROVED vacations

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#303]
Do not allow to cancel own APPROVED vacations (relevant for calendar screen). For profile screen, supervisor should be able to cancel it.

**Comment by antonm76** [comment]
Doesn't it look like a duplicate of #300?

**Comment by sponkrashin** [comment]
That issue is about server side, and this one is about mobile side.

**Comment by antonm76** [comment]
Right!

**Comment by sponkrashin** [comment]
From related issue #300: added new permission CancelApprovedCalendarEvents.

**Comment by antonm76** [comment]
Done. a08602272409c49cfc30d4407e10d5be4c2ad111

**Comment by KuchaLeni** [comment]
Verified.
