### ISSUE TITLE
Deal with avatars caching

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#306]
Consider using https://www.npmjs.com/package/react-native-cached-image to cache avatars

**Comment by YaroTs** [comment]
I've faced lots of mistakes trying to integrate this library. https://github.com/DylanVann/react-native-fast-image seems to be a better solution.

**Comment by YaroTs** [comment]
develop/ dbc688260762f54934f0967a871355e681322c7c

**Comment by KuchaLeni** [comment]
Fixed
