### ISSUE TITLE
Handle 503 errors with a proper message and retry option

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#337]
Server now should return 503 in case of all timeout errors (that includes cases when server is down). We should display a proper message for that, something along these lines:
'Server is unavailable at the moment, please try again later'
+ Retry button (there should be a functionality for that already implemented)

**Comment by KuchaLeni** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/28759011/53428494-f286b600-39fb-11e9-88fc-a12f4d3b12c5.png)
