### ISSUE TITLE
iOS: refactor login procedure

### ISSUE THREAD

**Issue by antonm76** [SoftwareCountry/arcadian-assistant#344]
Currently on iOS login procedure doesn't support edge cases: login errors, cancellation etc. Application either generates an error or jus stays on the SplashScreen. See screen recordings attached.
@YaroTs please consider using a scheme similar to what we have in Android.
@santee
![ios-login-1](https://user-images.githubusercontent.com/6681817/49644832-bfe7a580-fa2a-11e8-9201-0c08e9d4675f.gif)
![ios-login-2](https://user-images.githubusercontent.com/6681817/49644833-bfe7a580-fa2a-11e8-80ba-bfcc99063397.gif)
![ios-login-3](https://user-images.githubusercontent.com/6681817/49644834-bfe7a580-fa2a-11e8-8ed3-b3a62d0c25fd.gif)
![ios-login-4](https://user-images.githubusercontent.com/6681817/49644835-c0803c00-fa2a-11e8-8967-a9e90e3d53c6.gif)

**Comment by YaroTs** [comment]
develop/ 90989d5fe178a6cfce7bfe2d54989d7bcaae39d4

**Comment by YaroTs** [comment]
39c8bcf487418e1d0cf653425d70d365cc5f0d0f

**Comment by KuchaLeni** [comment]
Related bug #570
