### ISSUE TITLE
Android: refactor login procedure

### ISSUE THREAD

**Issue by antonm76** [SoftwareCountry/arcadian-assistant#345]
Currently on Android login procedure doesn't support returning back from a browser. See screen recordings attached.
I believe it is related to @santee 's component processing intent from a browser. Notice that tapping Cancel on the fingerprint dialog brings user properly to the Welcome screen
@santee
![android-login-1](https://user-images.githubusercontent.com/6681817/49645872-700add80-fa2e-11e8-870a-4a5e59283004.gif)
![android-login-3](https://user-images.githubusercontent.com/6681817/49645873-700add80-fa2e-11e8-8266-7fc9c362d4fd.gif)

**Comment by YaroTs** [comment]
develop/ 90989d5fe178a6cfce7bfe2d54989d7bcaae39d4

**Comment by YaroTs** [comment]
39c8bcf487418e1d0cf653425d70d365cc5f0d0f
