### ISSUE TITLE
Search: add text/icon when the search result is empty

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#348]
The blank page is displayed when the search result is empty. It looks like the data is still loading.
![search](https://user-images.githubusercontent.com/28759011/49727920-772a2980-fc82-11e8-9c28-8c7720dec554.png)

**Comment by antonm76** [comment]
@DesmanLead , @YaroTs I believe FlatList's ListEmptyComponent attribute would do the trick.

**Comment by YaroTs** [comment]
![screenshot 2018-12-10 at 14 50 17](https://user-images.githubusercontent.com/5641071/49730983-fa4f7d80-fc8a-11e8-8c7c-a75551bb8857.png)

**Comment by antonm76** [comment]
@YaroTs I would centre it. @santee do you know any component library providing fancy empty list component?

**Comment by YaroTs** [comment]
0b43c78a24963c532721a9f72c9344503d75897c

**Comment by KuchaLeni** [comment]
fixed
