### ISSUE TITLE
Profile view: Change the name of the button from "Organization" to "Company"

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#350]
![2018-12-10_1635](https://user-images.githubusercontent.com/28759011/49735901-a0a27f80-fc99-11e8-91e2-a920fa6eff33.png)

**Comment by YaroTs** [comment]
baf6dc3f7c6344a8756bef7c3e31297fa154d7a2

**Comment by KuchaLeni** [comment]
Verified
