### ISSUE TITLE
Send email notifications about calendar event changes

### ISSUE THREAD

**Issue by sponkrashin** [SoftwareCountry/arcadian-assistant#354]
Send email notifications about all changes in calendar events (created, cancelled, rejected, approved, user approve granted, completed and so on).

Related to issue #232

**Comment by sponkrashin** [comment]
@santee, which notifications do we need?
I suggest to start with the following:
1) When event is assigned to some approver - send notification to the approver
2) When event status is changed not by owner - send notification to employee of that event
3) When event is changed by owner - send notification to currently assigned approver

**Comment by santee** [comment]
looks good.
+ When new approval granted, send notification to owner.

**Comment by KuchaLeni** [comment]
Verified.
If final approval has been made in the database, only a vacation status change notification will be sent.
