### ISSUE TITLE
Profile view: title 'Daysoff available' is not updated according to summary quantity of daysoff and workouts

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#356]
- Title 'daysoff available' is displayed **on calendar view** when quantity of workouts >quantity of daysoff . 
- Title 'daysoff return' is displayed **on calendar view** when quantity of daysoff >quantity of workouts.

- Title 'daysoff available' is displayed **on profile view** in both case.

Expected result: title 'Daysoff available' is updated according to summary quantity of daysoff and workouts

![do](https://user-images.githubusercontent.com/28759011/49875814-fe1e0400-fe32-11e8-8f8d-12e2a447a6a9.jpg)
![do1](https://user-images.githubusercontent.com/28759011/49875815-fe1e0400-fe32-11e8-86e4-65f3302718ba.jpg)

**Comment by antonm76** [comment]
@KuchaLeni do you mean that titles on the calendar view are reverted?

**Comment by KuchaLeni** [comment]
yes, the title is not constant

**Comment by antonm76** [comment]
Done. d566bb8df5239b836fec372c81cc109c5673b6be

**Comment by KuchaLeni** [comment]
Fixed
