### ISSUE TITLE
Fix how calendar events dates can be changed

### ISSUE THREAD

**Issue by sponkrashin** [SoftwareCountry/arcadian-assistant#359]
How it is working now:

Sick Leave
Start date cannot be changed at all. When end date is changed, `SickLeaveProlonged` event is persisted. No current status checks.
 
Work Hours
Dates cannot be changed at all even in requested status.
 
Vacation
No checks at all. Dates can be changed in all statuses. When dates are changed, `VacationDatesAreEdited` event is persisted.

How I suggest to fix it:

User should be able to change dates for all calendar event types in Requested status. In this case `...DatesAreEdited` event should be persisted.
But user should not have ability to change dates if event has at least one user approval.

Sick Leave
When in Approved status it should be possible to change end date with `SickLeaveProlonged` event persisted. In other statuses this ability should be restricted.

Work Hours
Dates cannot be changed in all statuses except Requested.

Vacation
Dates cannot be changed in all statuses except Requested.

**Comment by sponkrashin** [comment]
@santee, any comments on this?

**Comment by santee** [comment]
Sick leave - leave as is

**Comment by santee** [comment]
Daysoff - leave as is

**Comment by santee** [comment]
Vacations can be edited in Requested status only

**Comment by KuchaLeni** [comment]
#511
