### ISSUE TITLE
User's preferences view: icon color changes 2 times after switching states

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#366]
The icon color (gray) turns white and then green when the email notification becomes active.
The icon color (green) turns white and then gray when the email notification becomes inactive.

**Comment by KuchaLeni** [comment]
Related issue #234

**Comment by YaroTs** [comment]
fc14bd98270695b3088344c3a4bb30ffe91d4fa9

**Comment by KuchaLeni** [comment]
fixed
