### ISSUE TITLE
Replace company search to use #375

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#381]
When searching on company view, result should be searching using server-side search (or all employees should be loaded on client). List should be displayed instead of tree.
While making server requests, do not forget to use searchPattern.debounceTime(1000).distinctUntilChanged().switchMap(). combination to decrease number of requests

**Comment by YaroTs** [comment]
483e1fa1acc8630e79a40d0d8886e3666746d171

**Comment by KuchaLeni** [comment]
Verified
