### ISSUE TITLE
Current day is displayed as end day of Vacation/Sick Leave by default

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#434]
1. Go to the app -> Calendar view
2. Click on some day in the future
3. Click on Request Vacation/Claim Sick Leave button

**Result:** Start day of Vacation/Sick Leave is a day from step 2, end day - current day by default
![photo_2019-01-23_18-55-29](https://user-images.githubusercontent.com/28759011/51619079-8f0ef180-1f40-11e9-8f5b-e847e54507e2.jpg)

**Expected result:**  start day of Vacation/Sick Leave is a day from step 2, end day - day from step 2 by default

**Comment by YaroTs** [comment]
0db303aaddd77c7be89cf797446fb94fcd992e7f

**Comment by KuchaLeni** [comment]
Fixed.
