### ISSUE TITLE
People view: Search is not cleared in some case

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#437]
1. Go to the People view
2. Enter some value in the search field
3. Go to some user from filtered list
4. Click on Company button on Profile view

**Result:** Company view opens with value in the search field from step 2

**Expected result:** Company view opens without value in the search field

**Comment by YaroTs** [comment]
I'm not sure if it's a bug or a normal behaviour. @santee What is desired behaviour in this case?

**Comment by santee** [comment]
Desired behavior is that click on room or a company from within profile screen empties a selection. Back should leave seatch intact. Reason is that typical use case would be - you find someone and want to see his place in hierarchy

**Comment by KuchaLeni** [comment]
Fixed
