### ISSUE TITLE
Notification settings change after sending requests and approving / rejecting requests

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#438]
**Precondition:** 
Device 1 - User 1 - employee, email notifications: on 
Device 2 - User 2 - supervisor of User 1, email notifications: off 

**Steps:**
1. Log in on Device 1 as User 1,  on Device 2 as User 2 
2. Go to the Calendar view on Device 1
3. Request Day off (or other event)
4. Go to the Profile view - User settings on Device 2
**Result:** email notifications: on
5. Turn off email notifications and go back to the Profile view
6. Approve/Reject Request from step 3
7. Go to Profile view - User settings on Device 1
**Result:** email notifications: off

**Expected result:** notification settings are changed only if the user has changed them.
**Bug is reproduced for push-notification (the same steps).**

**Comment by antonm76** [comment]
@sponkrashin looks like a server issue. Check an attached gif.

**Comment by antonm76** [comment]
![preferences](https://user-images.githubusercontent.com/6681817/52050383-76669300-2561-11e9-8883-4a2b58e7fda9.gif)

**Comment by KuchaLeni** [comment]
Fixed
