### ISSUE TITLE
Calendar view: user can't edit vacation dates

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#444]
1. Log in to the app
2. Go to the Calendar view
3. Request Vacation
4. Select some vacation date and click 'edit vacation' button 
5. Click on Change button
6. Change vacation dates and click on Confirm button

**Result:** 400 error is displayed, vacation dates are not changed.
![image](https://user-images.githubusercontent.com/28759011/52062741-2815bc00-2582-11e9-80d7-d456966e5889.png)

**Comment by KuchaLeni** [comment]
Reopened. Bug is reproduced.
![image](https://user-images.githubusercontent.com/28759011/53562207-df8df600-3b61-11e9-9d79-b4f469df08ab.png)

**Comment by sponkrashin** [comment]
@antonm76, the same question, what request is sent? I tried in Swagger and attempt was successful.

**Comment by KuchaLeni** [comment]
Fixed
