### ISSUE TITLE
Ajax error is displayed when user opens app in airplane mode 

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#446]
1. Log in to the app
2. Close the app
3. Delete app from the background
4. Turn on Airplane mode
5. Open the app

**Result:** Ajax error is displayed. User is logged out.

iOS behavior: No errors, user is logged in

![image](https://user-images.githubusercontent.com/28759011/52119039-f0158400-2628-11e9-8762-373df44de6ea.png)

**Comment by KuchaLeni** [comment]
Related issue #345

**Comment by antonm76** [comment]
I believe it is covered by the #344

**Comment by KuchaLeni** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/28759011/53561796-d2bcd280-3b60-11e9-8207-8e79d3e135a2.png)
