### ISSUE TITLE
Welcome screen is different on Android and iOS

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#447]
Button login with white background on iOS and blue background on Android 
![image](https://user-images.githubusercontent.com/28759011/52121750-bac16400-2631-11e9-9e4a-182eb7a2681a.png)
![image](https://user-images.githubusercontent.com/28759011/52121763-c6148f80-2631-11e9-9f24-fb57928d79e9.png)

**Comment by antonm76** [comment]
@santee Doesn't look like an issue

**Comment by sponkrashin** [comment]
If to be a nerd, fonts are different in both applications, also button is rounded in iOS and squared in Android :)

**Comment by KuchaLeni** [comment]
Fixed
