### ISSUE TITLE
There is no warning when a user cannot continue logging in due to network loss

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#448]
1. Log in to the app
2. Close the app
3. Delete app from the background
4. Turn on Airplane mode
5. Open the app

**Result:** welcome screen is displayed, no messages about connection to the server.

![image](https://user-images.githubusercontent.com/28759011/52122074-ce20ff00-2632-11e9-8175-ce8cb405ba81.png)

**Comment by KuchaLeni** [comment]
Related issue #344

**Comment by antonm76** [comment]
I believe #430 covers this case

**Comment by YaroTs** [comment]
Can't reproduce. There were a number of changes to auth process since 1 february, so this issue seems to be fixed.
![screenshot 2019-03-04 at 14 18 00](https://user-images.githubusercontent.com/5641071/53730314-9fdc4c80-3e88-11e9-98b2-b711207af779.png)

**Comment by KuchaLeni** [comment]
Fixed
