### ISSUE TITLE
Search on tabs Department/Room and Company is different

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#450]
**On Department/Room tabs:**
- search text in the beginning of a string
- search text in the middle of a string
- search employee position

**On Company tab**
- search text only in the beginning of a string

**Comment by YaroTs** [comment]
#381

**Comment by YaroTs** [comment]
@santee is it a bug or feature?

**Comment by santee** [comment]
Should always search in surname and first name beginning. Lets enable position search as well (beginning)

**Comment by KuchaLeni** [comment]
Fixed
