### ISSUE TITLE
Company view: Employee photo don't fit in the photo area

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#455]
**Device:** Samsung SM-G925F, Android 7

![image](https://user-images.githubusercontent.com/28759011/52644962-e4f80900-2ef0-11e9-85c3-29652d17173d.png)

**Comment by antonm76** [comment]
@KuchaLeni I need the device you used for testing.

**Comment by KuchaLeni** [comment]
Fixed.

**Comment by KuchaLeni** [comment]
Reopened. Device: Samsung SM-G925F, Android 7
![image](https://user-images.githubusercontent.com/28759011/54700618-6b34ea00-4b44-11e9-8044-c3d84f0518fd.png)

**Comment by KuchaLeni** [comment]
Related bug #535
