### ISSUE TITLE
Support 'processed' vacations

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#471]
There is a new status 'Processed' (? or something, ask @sponkrashin) for vacations
The logic should change as follows:
1. if the vacation is processed, nobody should be able to cancel it
2. processed vacations should be displayed in a different color (i suggest to change a color of 'approved' status instead, give it some opacity)

@sponkrashin remind me, anything else?

**Comment by antonm76** [comment]
@santee if vacation is processed, is it still possible to reject it, if there are enough permissions?

**Comment by sponkrashin** [comment]
Yes, everything is correct. Status is "Processed", API doesn't allow to change dates or statuses of vacation, if it is already in that status.

**Comment by KuchaLeni** [comment]
Verified
