### ISSUE TITLE
Push notification settings are enabled when the user has disabled notifications.

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#476]
Open the newly installed application? log in and click on "Don't Allow".
Then go to the user profile -> notification settings
Result: email notification and push notification are enabled.
Expected result:  email notification and push notification are disabled.

![image](https://user-images.githubusercontent.com/28759011/53346080-5c815b80-3927-11e9-8ca3-25ddf6c01d30.png)

![image](https://user-images.githubusercontent.com/28759011/53346075-57bca780-3927-11e9-8ca0-48efb7c98272.png)

**Comment by sponkrashin** [comment]
These settings are not related to each other. If I understand correct, "Don't allow" means that you change your system settings and prohibit application to receive push notifications at all.

**Comment by sponkrashin** [comment]
@KuchaLeni, it is like the VK app. If you switch push notifications off for the VK app in system settings, you will still be able to change notifications inside the app, messages, likes, friends and so on.

**Comment by santee** [comment]
not a bug.
