### ISSUE TITLE
Dayoff and Sickleave requests do not reach the supervisor

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#480]
1. Log in to the app
2. Go to calendar view
3. Create dayoff/sickleave
4. Go to the app as supervisor of user from step 1
5. Open profile view

**Result:**
Event from step 3 is not displayed in Requests list

**Expected result:**
Event from step 3 is displayed in Requests list

**Comment by KuchaLeni** [comment]
Reopened

**Comment by sponkrashin** [comment]
Re-resolved. Fixed.
Commit effdf2fe7bed949a0c63eb3ce505a43e913fd862

**Comment by KuchaLeni** [comment]
Fixed.
