### ISSUE TITLE
Processed vacation does not have status 

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#482]
Blank line is displayed instead of event status (for ex. 'has coming vacation')
![image](https://user-images.githubusercontent.com/28759011/53477882-b187b380-3a86-11e9-8cc9-2de8a1a3b9e3.png)

**Comment by antonm76** [comment]
@KuchaLeni it would be great to have a mobile label set on this issue -)

**Comment by santee** [comment]
right... in that case, approved vacations should be displayed the same as requested (including style and text).
'has coming vacation' should be displayed for processed events.

**Comment by antonm76** [comment]
@santee Node, already implemented it this way -)

**Comment by sponkrashin** [comment]
Maybe for Approved it should be like "Sent to accounting department"?

**Comment by santee** [comment]
no.

**Comment by sponkrashin** [comment]
@antonm76, as I can see in 9a521de298d49e59ecc71431b73f4ec84dc32221 approved and processed vacations has the same status for now. But as I understood, @santee meant that Approved should become as Requested and Processed as Approved.

**Comment by antonm76** [comment]
@sponkrashin yes, and it looks that @santee just misspelled, he also said "
'has coming vacation' should be displayed for processed events" and this corresponds to Approved. And as far as I can see, Processed is more like Approved than Requested, cause it happens when request it Approved.

**Comment by sponkrashin** [comment]
I think it is not misspell.

> 'has coming ...' should be displayed for processed

> approved vacations should be displayed the same as requested

All is clear, as for me :)

**Comment by antonm76** [comment]
you are right

**Comment by KuchaLeni** [comment]
Fixed
