### ISSUE TITLE
'Prolong sick leave' feature fails with 400 error

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#492]
Go to the app as user 1
Open calendar view
Claim Sick Leave
Go to the app as supervisor or user 1
Go to profile view and approve Sick Leave
Go to the app as user 1
Go to calendar view and try to prolong Sick Leave

**Result:** 400 error is displayed.
![image](https://user-images.githubusercontent.com/28759011/53552982-a3509a80-3b4d-11e9-92fb-5aff92aedb6b.png)

**Comment by sponkrashin** [comment]
@antonm76, what request is sent from client to server in the case of sick leave prolongation? I'm the most interested in Status field to be exact.

**Comment by antonm76** [comment]
@sponkrashin let me check

**Comment by sponkrashin** [comment]
@antonm76?

**Comment by antonm76** [comment]
@sponkrashin be patient, grow your Dao

**Comment by sponkrashin** [comment]
Ommmmmmmmm....

**Comment by antonm76** [comment]
{"calendarEventId":"2cc3e8e3-6d57-4f72-8f00-6c35efe6c677","type":"Sickleave","dates":{"startDate":"03/04/2019","endDate":"03/11/2019","startWorkingHour":0,"finishWorkingHour":0},"status":"Approved"}

**Comment by sponkrashin** [comment]
**endDate** attribute has constraint on value range from 1 to 24.

**Comment by sponkrashin** [comment]
Could you check what error is returned when you try to prolong sick leave?

**Comment by antonm76** [comment]
<img width="645" alt="screenshot 2019-02-28 at 15 57 31" src="https://user-images.githubusercontent.com/6681817/53567870-99409300-3b71-11e9-882d-bed8f3208634.png">

**Comment by sponkrashin** [comment]
Gotcha!

**Comment by antonm76** [comment]
BTW, I noticed that finishWorkingHour became 0, wasn't sure it is important. Is it important for this particular case?

**Comment by sponkrashin** [comment]
Working hours are needed only for work hours event type. For all other cases they could have their default values: 0 and 8.

**Comment by KuchaLeni** [comment]
Fixed
