### ISSUE TITLE
Vacation status in mobile app did not change after approve/cancel in the cspdb

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#495]
1. - Go to the http://arcadiacspdb00v/ as employee -> Profile-> Vacations
2. - Create  vacation
3. - Go to the mobile app as manager of the employee and check that request is displayed.
4. - Go back to the  http://arcadiacspdb00v/ as manager of the employee and approve the vacation
5. - Go to the mobile app as director of the employee and check that request is displayed.
6. - Go to the mobile app as manager of the employee and go to the profile view

**Result:**  request is displayed. Manager can approve/reject vacation.

**Comment by sponkrashin** [comment]
Fixed in 8cf6e0bd096bd365d621864a44f5b6e635a1e923.

**Comment by KuchaLeni** [comment]
Fixed
