### ISSUE TITLE
"Change" button is available after approval of the vacation by manager

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#511]
Go to the app as employee
Go to the calendar view and create vacation
Go to the app as manager of employee from step 1 and approve vacation
Go to the app as employee and open Calendar view
Click on vacation from step 2
Click on Edit Vacation button
Click on Change button
Change date range of vacation

**Result:**
400 error is displayed, date is not updated.

**Expected result:**
'Change' button is disabled

**Comment by antonm76** [comment]
@KuchaLeni the 'Edit Vacation' button disabled status is controlled by the following condition:
```
interval.calendarEvent.isCompleted || interval.calendarEvent.isApproved
```
So, the question is, whether you refreshed events in "app as employee" before changing it or not. For me it looks like legitimate behaviour. @santee probably we have to refresh user's events upon going to the Calendar tab?

**Comment by antonm76** [comment]
I would emit refresh action in two cases, actually:
1. When app goes foreground
2. When user goes to the Calendar tab

**Comment by KuchaLeni** [comment]
Fixed
