### ISSUE TITLE
Events canceled by initiators are displayed in supervisor profile

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#513]
1. Go to the app 
2. Open calendar view and create vacation/day off/sick leave
3. Cancel created event
4. Go to profile - created event is not displayed
5. Go to the app as supervisor of employee 
6. Open profile view

**Result**
Canceled event is displayed in Profile view

**Comment by KuchaLeni** [comment]
Related bug #510

**Comment by sponkrashin** [comment]
Probably, is not a server bug. After event cancellation all server APIs (pending requests and events for specific employee) return list without cancelled event.

**Comment by antonm76** [comment]
Doesn't look like an issue. Profile view refreshes correctly.
![513](https://user-images.githubusercontent.com/6681817/53738207-9f9b7b80-3e9f-11e9-89da-c413f4cb6bd1.gif)

**Comment by sponkrashin** [comment]
Yes, it is server bug.

**Comment by KuchaLeni** [comment]
Fixed

**Comment by KuchaLeni** [comment]
Fixed
