### ISSUE TITLE
Application stops working after changing employee email

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#514]
Go to DB and change employee email

**Result:**
For employee with changed email - "Authorization error" is displayed
For other employees - '500 error' is displayed

**Comment by sponkrashin** [comment]
I don't think it is a bug. It's highly likely that email will not be changed ever.
@santee?

**Comment by santee** [comment]
figure out why.

**Comment by sponkrashin** [comment]
403 is predictable behavior, email from authorization context doesn't match email in database.
500 - is not reproduced.

**Comment by KuchaLeni** [comment]
![image](https://user-images.githubusercontent.com/28759011/53740166-a4aef980-3ea4-11e9-9a9a-40134d446cc9.png)

**Comment by antonm76** [comment]
Application tries to register itself for push notifications.

**Comment by sponkrashin** [comment]
Ok, we've found it out. 500 happens when email is duplicated, i.e. two employees have the same email. Such case is impossible.

**Comment by santee** [comment]
Does it break an application for everybody or just this user? If only one user, probably fine.

**Comment by sponkrashin** [comment]
Only for those users that has identical emails.
