### ISSUE TITLE
'Server is not available' error displays after creating event

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#537]
Go to the calendar view and create event
**Result:**
'Server is not available' error is displayed. 
1. Close error window.
2. Go to the profile view and refresh the page -> event is displayed in 'Events' list
![image](https://user-images.githubusercontent.com/28759011/54117404-ba22a700-4401-11e9-81b7-8ce06e81bcd5.png)

**Comment by sponkrashin** [comment]
Fixed in 107d1c176a0c5dbdee30e4d8d8c10793923fbf4e

**Comment by KuchaLeni** [comment]
Fixed
