### ISSUE TITLE
Add vacation cancel reason to push notification

### ISSUE THREAD

**Issue by sponkrashin** [SoftwareCountry/arcadian-assistant#549]
If vacation cancel reason is set in CSP database, it should be added to push notification when vacation is cancelled.

**Comment by sponkrashin** [comment]
If vacation cancel reason is set in CSP database, it should be added to push notification when vacation is cancelled.

**Comment by KuchaLeni** [comment]
Reopened.
![image](https://user-images.githubusercontent.com/28759011/55564722-3064b180-5701-11e9-99cf-0ad15d0c294d.png)
![image](https://user-images.githubusercontent.com/28759011/55564767-4d00e980-5701-11e9-9fcc-2d4990439952.png)

**Comment by sponkrashin** [comment]
Deployment problems. Now it works.

**Comment by KuchaLeni** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/28759011/55872354-73a5a100-5b95-11e9-82ca-a1c3409fbf54.png)
![image](https://user-images.githubusercontent.com/28759011/55872410-93d56000-5b95-11e9-9c21-a1d771f0d55a.png)
