### ISSUE TITLE
Calendar view: should be able to change the first day of vacation after clicking on the “Request Vacation” button

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#554]
**Actual result:** The user can't change the first day of vacation after clicking on the “Request Vacation” button.
**Expected result:** The user should be able to select (or change) the first day of vacation after clicking on the “Request Vacation” button.

**Comment by antonm76** [comment]
@santee said to do this way!!!

**Comment by KuchaLeni** [comment]
Errare humanum est :)

**Comment by DesmanLead** [comment]
Will be fixed with #672

**Comment by KuchaLeni** [comment]
Fixed
