### ISSUE TITLE
People view: long room name does not fit in tab title

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#571]
Bug is reproduced on devices with small screen (for ex. Samsung sm-g925f)

![image](https://user-images.githubusercontent.com/28759011/55332546-4de61100-549e-11e9-8716-41ea3e202e9a.png)
![image](https://user-images.githubusercontent.com/28759011/55332630-753cde00-549e-11e9-952c-6dfea21d9a96.png)

**Comment by DesmanLead** [comment]
@antonm76 @YaroTs we can add “Room” prefix only in case room name is a number. So in this case it will be just “Taganrog”.

**Comment by victor-kotov-arcadia** [comment]
Hi, we've tried to find some simple and elegant solution for this case during the daily meeting and want to discuss this one:

1. Remove room detailed info here:
![2019-04-09_15-36-35](https://user-images.githubusercontent.com/8047237/55800968-a12f1380-5add-11e9-866e-d0f846fab4f0.png)

So it became just "Room" not "Room Taganrog"

2. Keep it fully detailed here:
![2019-04-09_15-37-10](https://user-images.githubusercontent.com/8047237/55801001-ba37c480-5add-11e9-9eaf-47f41f45de12.png)

@santee @KuchaLeni please let us know your thoughts.

**Comment by antonm76** [comment]
@santee @KuchaLeni actually, it would revert changes we made earlier and make tab titles to be "Department", "Room" and "Company" while still keep department and room names on corresponding screens.
We haven't been able to come up with a better solution.

**Comment by KuchaLeni** [comment]
Fixed
