### ISSUE TITLE
Approved sick leave notification: add additional employee identification in email

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#597]
Add additional employee identification in accounting email about approved sick leave, for ex. Employee ID (This is necessary to distinguish between employees with the same name and surname).

**Comment by sponkrashin** [comment]
@santee, any thoughts?

**Comment by santee** [comment]
employee id

**Comment by KuchaLeni** [comment]
Fixed
![image](https://user-images.githubusercontent.com/28759011/60026213-d8a46980-96a3-11e9-851f-4b3fba6db99d.png)
