### ISSUE TITLE
Calendar view: Delete 'Completed' button for Sick leaves

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#609]
Only HR should be able to complete sick leaves in cspdb

**Comment by KuchaLeni** [comment]
Related issue #603

**Comment by KuchaLeni** [comment]
Reopened. Button must be deleted, not disabled.
![image](https://user-images.githubusercontent.com/28759011/56567844-70aba700-65be-11e9-95ad-9c1d12208b42.png)

**Comment by antonm76** [comment]
@victor-kotov-arcadia according to @KuchaLeni, current business logic just doesn't suppose any user to complete his/her sick leave, so just remove this button from this dialog and that's it.

**Comment by KuchaLeni** [comment]
![image](https://user-images.githubusercontent.com/28759011/60178852-09f87300-9825-11e9-9769-254fea8c48cf.png)
