### ISSUE TITLE
DB, Calendar view: Record about prolonged sick leave appears in [dbo].[SickLeaveAccepts]

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#610]
[dbo].[SickLeaveAccepts] table contains information about approved sick leaves by supervisor.
![image](https://user-images.githubusercontent.com/28759011/56134090-886ba580-5f96-11e9-8192-1f19d0e0cb6a.png)

**Comment by sponkrashin** [comment]
@antonm76, what request do you send from client-side when prolonging sick leave? I tested in Swagger, it doesn't has any side-effects.

**Comment by antonm76** [comment]
@sponkrashin it is a following:
```
PUT /employees/2236/events/Sickleave_20
```
with a following request body:
```
{"calendarEventId":"Sickleave_20","type":"Sickleave","dates":{"startDate":"04/21/2019","endDate":"04/26/2019","startWorkingHour":0,"finishWorkingHour":8},"status":"Approved"}
```

**Comment by sponkrashin** [comment]
Ok, thanks. So then it is server bug, it doesn't check that event was already approved.

**Comment by KuchaLeni** [comment]
Fixed
