### ISSUE TITLE
PIN code: Add logout button on protection screen

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#618]
User should be able to log out without entering the wrong pin codes.
![image](https://user-images.githubusercontent.com/28759011/56353950-467f7100-61db-11e9-8088-f7da88c22131.png)

**Comment by YaroTs** [comment]
@antonm76 @KuchaLeni @DesmanLead 

Is such implementation ok?

![Screenshot 2019-04-18 at 15 58 34](https://user-images.githubusercontent.com/5641071/56362788-5905a480-61f3-11e9-91d2-d26e772367e3.png)

Also do we need an ability to log out on this screen? 

![Screenshot 2019-04-18 at 16 00 47](https://user-images.githubusercontent.com/5641071/56362952-b699f100-61f3-11e9-95c2-16424e413887.png)

**Comment by KuchaLeni** [comment]
@YaroTs, 
1) Maybe better to use the logout icon with label (as for the 'delete')?
2) Yes, we also need ability to log out from the second screen.

**Comment by YaroTs** [comment]
@KuchaLeni Is it better now?

![Screenshot 2019-04-18 at 16 51 57](https://user-images.githubusercontent.com/5641071/56365825-6eca9800-61fa-11e9-8382-fb6659331bb2.png)

**Comment by KuchaLeni** [comment]
@YaroTs yes, it's good

**Comment by KuchaLeni** [comment]
Fixed
