### ISSUE TITLE
PIN Code: 'Feeds' view is opened with a biometric data request

### ISSUE THREAD

**Issue by KuchaLeni** [SoftwareCountry/arcadian-assistant#623]
1. Install version of the app without pin code protection
2. Log in to the app
3. Install new version of the app with pin code protection
4. Set PIN Code

**Result:**
'Feeds' view is opened with a biometric data request
![image](https://user-images.githubusercontent.com/28759011/56359295-d0363b00-61e9-11e9-809a-fa0618a2af8b.png)

**Expected result:**
Biometric data request is not displayed on 'Feeds' view

**Comment by antonm76** [comment]
Doesn't worth to fix
