### ISSUE TITLE
Add sick leave end date to accounting notification

### ISSUE THREAD

**Issue by sponkrashin** [SoftwareCountry/arcadian-assistant#637]

**Comment by KuchaLeni** [comment]
![image](https://user-images.githubusercontent.com/28759011/60025803-105ee180-96a3-11e9-9632-a39dda14c08f.png)
![image](https://user-images.githubusercontent.com/28759011/60025816-181e8600-96a3-11e9-8dc2-5cebaad62ab1.png)
