### ISSUE TITLE
Add sick leave prolong accounting notification

### ISSUE THREAD

**Issue by sponkrashin** [SoftwareCountry/arcadian-assistant#638]
When sick leave is prolonged by employee, notification email should be sent to accounting department.

**Comment by santee** [comment]
@sponkrashin add description :)

**Comment by santee** [comment]
accounting dep should be notified about sick leaves prolongation, I guess

**Comment by sponkrashin** [comment]
Right.

**Comment by KuchaLeni** [comment]
Fixed
![image](https://user-images.githubusercontent.com/28759011/60025666-c70e9200-96a2-11e9-9703-4448d418c060.png)
