### ISSUE TITLE
Handle new release notifications

### ISSUE THREAD

**Issue by DesmanLead** [SoftwareCountry/arcadian-assistant#671]
Mobile part of #656

**Comment by sponkrashin** [comment]
After new build is downloaded by server , push notification will be sent with custom data parameter `Type = "UpdateAvailable"`.

**Comment by DesmanLead** [comment]
@sponkrashin `Type`, not `type`? All other fields look like: `employeeId`, `approverId`.

**Comment by sponkrashin** [comment]
I send it as "Type", but serializer, probably, makes "type" from it. Anyway, all is the same as for other notifications.

**Comment by antonm76** [comment]
@YaroTs the full list of notification types can be found here: https://github.com/SoftwareCountry/arcadian-assistant/blob/master/server/Arcadia.Assistant.Calendar.Notifications/CalendarEventPushNotificationTypes.cs

**Comment by KuchaLeni** [comment]
Android:
![image](https://user-images.githubusercontent.com/28759011/60724848-26409200-9f40-11e9-86b7-e1df110a5c21.png)

iOS:
![image](https://user-images.githubusercontent.com/28759011/60725173-0f4e6f80-9f41-11e9-9e0a-e06c47e3365e.png)
