### ISSUE TITLE
Revert vacation dialogs flow

### ISSUE THREAD

**Issue by DesmanLead** [SoftwareCountry/arcadian-assistant#672]
Revert first dialog with start day selection.
See 22e5f4e63222c2157a937848ec3f4ea77e6367a9

**Comment by KuchaLeni** [comment]
Fixed
![image](https://user-images.githubusercontent.com/28759011/60655631-c6ba8780-9e56-11e9-917e-4f4d2b39037b.png)
![image](https://user-images.githubusercontent.com/28759011/60655649-d1751c80-9e56-11e9-917c-36f8e0d22823.png)
![image](https://user-images.githubusercontent.com/28759011/60655684-ddf97500-9e56-11e9-97b7-3003850549b3.png)
