### ISSUE TITLE
Calendar: mark today

### ISSUE THREAD

**Issue by DesmanLead** [SoftwareCountry/arcadian-assistant#676]
Probably making it bold will be fine.

**Comment by KuchaLeni** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/28759011/60025433-49e31d00-96a2-11e9-974c-b3bc5cc0fef2.png)
![image](https://user-images.githubusercontent.com/28759011/60025446-4fd8fe00-96a2-11e9-8a9a-275e0a520990.png)
