### ISSUE TITLE
Remove approval step from sick-leaves

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#679]
Following changes need to be implemented:
1. No approval is required in sick-leave (mobile should display it as approved immediately). @DesmanLead see if you want to create a separate task to track it
2. Email to HR should be sent upon sick leave submission
3. Notification (push/email) should be sent to a manager upon submission
4. Emails to HR (and manager) should be sent whenever it's prolonged or cancelled

**Comment by sponkrashin** [comment]
1. Will probably be done automatically, because server will return event with status Approved on create request like it works for all Baklan requests for now.

**Comment by KuchaLeni** [comment]
Related issues: #712

**Comment by KuchaLeni** [comment]
Fixed
