### ISSUE TITLE
Profile: add events status description

### ISSUE THREAD

**Issue by DesmanLead** [SoftwareCountry/arcadian-assistant#691]
**Vacation**
*  "Requested" waiting for approvals
*  "Approved" preparing documents
*  "Cancelled" cancelled
*  "Rejected" rejected
*  "AccountingReady" documents are ready to sign
*  "Processed" confirmed

**Dayoff / Workout**
*  "Requested" waiting for approvals
*  "Approved" confirmed
*  "Cancelled" cancelled
*  "Rejected" rejected

**Sickleave**
*  "Requested" confirmed
*  "Completed" completed
*  "Cancelled" cancelled

**Comment by KuchaLeni** [comment]
Fixed
