### ISSUE TITLE
Change vacations approval process

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#694]
Change vacations approval as follows:
1. Only one approval is required for request to be approved
2. Upon creation it goes to direct manager's pending actions list
3. If request is not approved in configured amount of working days (say, 3 days by default), it goes to the next approver's pending actions list (but stays in manager's list though).

**Comment by sponkrashin** [comment]
Approvals work the following way:
All event types need one approval of any employee that have rights to do it.
Vacations have specific flow - if assigned approver won't approve event after some days (3 by default settings), event is assigned to next approver from departments hierarchy (for my event approvers are Shevnin, Maxim, Efimova, Baklan), but it still is shown in previous approver pending actions list.

**Comment by KuchaLeni** [comment]
Fixed
