### ISSUE TITLE
Add new fields to Push Notifications custom fields

### ISSUE THREAD

**Issue by antonm76** [SoftwareCountry/arcadian-assistant#704]
Currently Push Notifications custom fields are not as consistent as wants them to be:

1. Only notification about new application version has "type" field. (type = "UpdateAvailable"). Is it possible to add notification type to other notifications to make it possible to compare them effectively?
2. It would be great if server provides url to be opened on a mobile device to download new application version, like url = "https://arcadia-assistant-dev.arcadialab.ru"

Related issues: #656, #671

**Comment by antonm76** [comment]
@YaroTs

**Comment by sponkrashin** [comment]
1. Server sends type in each push notification custom data (like in "event assigned to approver" notification, https://github.com/SoftwareCountry/arcadian-assistant/blob/master/server/Arcadia.Assistant.Calendar.Notifications/EventAssignedToApproverPushNotificationActor.cs#L121).

**Comment by antonm76** [comment]
Huh, good to know, thx! Eager to know why don't we use them in our code.
@YaroTs the full list of notification types can be found here: https://github.com/SoftwareCountry/arcadian-assistant/blob/master/server/Arcadia.Assistant.Calendar.Notifications/CalendarEventPushNotificationTypes.cs

**Comment by antonm76** [comment]
Invalid
